name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: ./reports/
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Add rendered file to Git repository 
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: updated acubed report from acubed-report 
          branch: main
          file_pattern: '*.pdf'
          repository: ./reports/
          create_branch: false
